## Basic Configuration

baseurl = "https://joonbum.netlify.app/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Joonbum Lee"
title = "Joonbum Lee"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-205272633-1"
enableRobotsTXT = true

## Site Settings
[params]
author = "Joonbum Lee"
intro = "Associate Scientist at the University of Wisconsin-Madison"
description = "I study drivers’ behavior with a focus on driver-automation collaboration, having published 24 journal papers, cited 970 times, and secured $2.7M in research funding."
authorimage = "CTL_headshot.jpg"
dateformat = "Sep 8, 2020"

## Site Meta Settings
[params.meta]
description = "Joonbum Lee"
keywords = "human factors"

## Social Accounts
[params.social]
#github = "<username>"
#instagram = "<username>"
#xing = "<username>"
linkedin = "joonbum-lee-22861445"
twitter = "JoonbumLee"
#facebook = "<username>"
#google = "<username>"
googlescholar = "If8VjuwAAAAJ"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"
#youtube = "<channelid>"
#keybase = "<username>"
#twitch = "<username>"
#soundcloud = "<username>"
#tumblr = "<username>"
#strava = "<username>"
#skype = "<username>"
#telegram = "<username>"
#whatsapp = "<username>"
email = "joonbum.lee@wisc.edu"
#pgp = "<key_fingerprint>"

## Extras
[params.extra]
copyright = "© 2020. Joonbum Lee. "
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "About me"
    identifier = "About"
    weight = 100
    url = "/About/"
#[[menu.main]]
#    name = "Lab"
#    identifier = "Lab"
#    weight = 200
#    url = "/DASH Lab/"
#[[menu.main]]
#    name = "Project"
#    identifier = "Project"
#    weight = 300
#    url = "/Project/"
#[[menu.main]]
#    name = "Publication"
#    identifier = "Publication"
#    weight = 400
#    url = "/Publication/"
#[[menu.main]]
#    name = "Teaching"
#    identifier = "Teaching"
#    weight = 500
#    url = "/Teaching/"
[[menu.main]]
    name = "CV"
    identifier = "CV"
    weight = 600
    url = "files/cv.pdf"
